# Generated by Django 5.1 on 2025-06-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0007_reembolso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre o reembolso, motivos, etc.', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='status',
            field=models.BooleanField(default=True, help_text='True se o reembolso foi efetivado, False caso contrário.', verbose_name='Status do Reembolso'),
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('tipo_documento', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('COMPROVANTE_RENDA', 'Comprovante de Renda'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('CONTRACHEQUE', 'Contracheque'), ('DECLARACAO_IR', 'Declaração Imposto de Renda'), ('OUTROS', 'Outros')], default='OUTROS', max_length=25, verbose_name='Tipo do Documento')),
                ('arquivo', models.FileField(upload_to='documentos_clientes/%Y/%m/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siape.cliente', verbose_name='Cliente')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Enviou')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos dos Clientes',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['cliente'], name='siape_docum_cliente_564e48_idx'), models.Index(fields=['tipo_documento'], name='siape_docum_tipo_do_52dbbc_idx'), models.Index(fields=['data_upload'], name='siape_docum_data_up_f1ee44_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTabulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('EM_NEGOCIACAO', 'Em Negociação - Padrão'), ('ANALISANDO_PROPOSTA', 'Analisando Proposta'), ('ESPERANDO_DOCUMENTOS', 'Esperando Documentos'), ('REVERSAO', 'Reversão'), ('VENDA_DIGITADA', 'Venda Digitada'), ('CHECAGEM', 'Checagem'), ('FINALIZADA', 'Finalizada')], max_length=25, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('EM_NEGOCIACAO', 'Em Negociação - Padrão'), ('ANALISANDO_PROPOSTA', 'Analisando Proposta'), ('ESPERANDO_DOCUMENTOS', 'Esperando Documentos'), ('REVERSAO', 'Reversão'), ('VENDA_DIGITADA', 'Venda Digitada'), ('CHECAGEM', 'Checagem'), ('FINALIZADA', 'Finalizada')], max_length=25, verbose_name='Status Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Alteração')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_tabulacoes', to='siape.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_tabulacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Histórico de Tabulação',
                'verbose_name_plural': 'Históricos de Tabulações',
                'ordering': ['-data_alteracao'],
                'indexes': [models.Index(fields=['cliente'], name='siape_histo_cliente_13513d_idx'), models.Index(fields=['data_alteracao'], name='siape_histo_data_al_482500_idx'), models.Index(fields=['usuario'], name='siape_histo_usuario_52cf20_idx')],
            },
        ),
        migrations.CreateModel(
            name='TabulacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_NEGOCIACAO', 'Em Negociação - Padrão'), ('ANALISANDO_PROPOSTA', 'Analisando Proposta'), ('ESPERANDO_DOCUMENTOS', 'Esperando Documentos'), ('REVERSAO', 'Reversão'), ('VENDA_DIGITADA', 'Venda Digitada'), ('CHECAGEM', 'Checagem'), ('FINALIZADA', 'Finalizada')], default='EM_NEGOCIACAO', max_length=25, verbose_name='Status da Tabulação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta é a tabulação atual do cliente', verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulacoes', to='siape.cliente', verbose_name='Cliente')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabulacoes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Tabulação do Cliente',
                'verbose_name_plural': 'Tabulações dos Clientes',
                'ordering': ['-data_atualizacao'],
                'indexes': [models.Index(fields=['cliente', 'ativo'], name='siape_tabul_cliente_950ea0_idx'), models.Index(fields=['status'], name='siape_tabul_status_428bcb_idx'), models.Index(fields=['data_atualizacao'], name='siape_tabul_data_at_487ec5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Formato: (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', max_length=15, verbose_name='Número do Telefone')),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('FIXO', 'Fixo'), ('COMERCIAL', 'Comercial'), ('RECADO', 'Recado')], default='CELULAR', max_length=10, verbose_name='Tipo de Telefone')),
                ('principal', models.BooleanField(default=False, verbose_name='Telefone Principal')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='siape.cliente', verbose_name='Cliente')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefones_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cadastrou')),
            ],
            options={
                'verbose_name': 'Telefone do Cliente',
                'verbose_name_plural': 'Telefones dos Clientes',
                'ordering': ['-principal', '-data_cadastro'],
                'indexes': [models.Index(fields=['cliente'], name='siape_telef_cliente_4a2ddc_idx'), models.Index(fields=['numero'], name='siape_telef_numero_50b4c6_idx'), models.Index(fields=['tipo'], name='siape_telef_tipo_d52e31_idx')],
                'unique_together': {('cliente', 'numero')},
            },
        ),
    ]
