# Generated by Django 5.1 on 2025-06-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0008_reembolso_observacoes_alter_reembolso_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentofichacliente',
            name='telefone_contato',
            field=models.CharField(blank=True, help_text='Telefone do cliente para contato relacionado ao agendamento', max_length=15, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='telefonecliente',
            name='agendamento_origem',
            field=models.ForeignKey(blank=True, help_text='Agendamento que originou este telefone (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefones_cadastrados', to='siape.agendamentofichacliente', verbose_name='Agendamento de Origem'),
        ),
        migrations.AddField(
            model_name='telefonecliente',
            name='origem',
            field=models.CharField(choices=[('AGENDAMENTO', 'Adicionado pelo Agendamento'), ('OUTROS', 'Adicionado por Outros Lugares')], default='OUTROS', help_text='Indica se o telefone foi adicionado pelo agendamento ou outros lugares', max_length=20, verbose_name='Origem do Cadastro'),
        ),
        migrations.AlterField(
            model_name='agendamentofichacliente',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('FECHOU', 'Fechou negócio'), ('NAO_QUIS', 'Não quis')], default='AGENDADO', max_length=15, verbose_name='Status do Agendamento'),
        ),
    ]
