# Generated by Django 5.1 on 2025-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0010_remove_tabulacaocliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicotabulacaoagendamento',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('SEM_RESPOSTA', 'Sem Resposta'), ('EM_NEGOCIACAO', 'Em Negociação'), ('REVERSAO', 'Reversão'), ('REVERTIDO', 'Revertido'), ('DESISTIU', 'Desistiu'), ('CHECAGEM', 'Checagem'), ('CHECAGEM_OK', 'Checagem OK'), ('ALTO_RISCO', 'Alto Risco'), ('CONCLUIDO_PG', 'Concluído PG')], max_length=25, null=True, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicotabulacaoagendamento',
            name='status_novo',
            field=models.CharField(choices=[('SEM_RESPOSTA', 'Sem Resposta'), ('EM_NEGOCIACAO', 'Em Negociação'), ('REVERSAO', 'Reversão'), ('REVERTIDO', 'Revertido'), ('DESISTIU', 'Desistiu'), ('CHECAGEM', 'Checagem'), ('CHECAGEM_OK', 'Checagem OK'), ('ALTO_RISCO', 'Alto Risco'), ('CONCLUIDO_PG', 'Concluído PG')], max_length=25, verbose_name='Status Novo'),
        ),
        migrations.AlterField(
            model_name='tabulacaoagendamento',
            name='status',
            field=models.CharField(choices=[('SEM_RESPOSTA', 'Sem Resposta'), ('EM_NEGOCIACAO', 'Em Negociação'), ('REVERSAO', 'Reversão'), ('REVERTIDO', 'Revertido'), ('DESISTIU', 'Desistiu'), ('CHECAGEM', 'Checagem'), ('CHECAGEM_OK', 'Checagem OK'), ('ALTO_RISCO', 'Alto Risco'), ('CONCLUIDO_PG', 'Concluído PG')], default='EM_NEGOCIACAO', max_length=25, verbose_name='Status da Tabulação'),
        ),
    ]
