# Generated by Django 5.1 on 2025-06-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0011_remove_tabulacaocliente_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabulacaoagendamento',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Máximo de 2000 caracteres', max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='DadosNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco')),
                ('valor_liberado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Liberado')),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Devedor')),
                ('parcela_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Parcela Atual')),
                ('parcela_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Parcela Nova')),
                ('tc', models.DecimalField(blank=True, decimal_places=2, help_text='Taxa de custo em percentual', max_digits=5, null=True, verbose_name='Taxa de Custo (%)')),
                ('troco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Troco')),
                ('prazo_atual', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo Atual (meses)')),
                ('prazo_acordado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo Acordado (meses)')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes adicionais sobre a negociação - máximo 3000 caracteres', max_length=3000, null=True, verbose_name='Descrição da Negociação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Modificação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dados_negociacao', to='siape.agendamentofichacliente', verbose_name='Agendamento')),
                ('tabulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dados_negociacao', to='siape.tabulacaoagendamento', verbose_name='Tabulação')),
            ],
            options={
                'verbose_name': 'Dados da Negociação',
                'verbose_name_plural': 'Dados das Negociações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_arquivo', models.CharField(max_length=255, verbose_name='Título do Arquivo')),
                ('arquivo', models.FileField(help_text='Arquivos relacionados à negociação', upload_to='arquivos_negociacao/%Y/%m/', verbose_name='Arquivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Modificação')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dados_negociacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='siape.dadosnegociacao', verbose_name='Dados da Negociação')),
            ],
            options={
                'verbose_name': 'Arquivo da Negociação',
                'verbose_name_plural': 'Arquivos das Negociações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='dadosnegociacao',
            index=models.Index(fields=['agendamento'], name='siape_dados_agendam_b2e232_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosnegociacao',
            index=models.Index(fields=['tabulacao'], name='siape_dados_tabulac_3f49a3_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosnegociacao',
            index=models.Index(fields=['data_criacao'], name='siape_dados_data_cr_801604_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosnegociacao',
            index=models.Index(fields=['banco_nome'], name='siape_dados_banco_n_2bcd6d_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivonegociacao',
            index=models.Index(fields=['dados_negociacao'], name='siape_arqui_dados_n_ef133c_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivonegociacao',
            index=models.Index(fields=['data_criacao'], name='siape_arqui_data_cr_a1d16b_idx'),
        ),
    ]
