# Generated by Django 5.1 on 2025-06-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0012_remove_tabulacaocliente_cliente_and_more'),
    ]

    operations = [
        # As tabelas TabulacaoCliente e HistoricoTabulacao já foram removidas na migração 0010
        # Esta migração foi gerada automaticamente mas não é necessária
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL command
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
