# Generated by Django 5.1 on 2025-06-24 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0013_remove_tabulacaocliente_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioChecagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data agendada para a checagem/reversão', verbose_name='Data da Checagem')),
                ('hora', models.TimeField(help_text='Hora agendada para a checagem/reversão (intervalos de 15 min entre 10h-17h)', verbose_name='Hora da Checagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data da Última Modificação')),
                ('observacao_consultor', models.TextField(blank=True, help_text='Observações do consultor sobre a checagem/reversão solicitada', null=True, verbose_name='Observação do Consultor')),
                ('observacao_coordenador', models.TextField(blank=True, help_text='Observações do coordenador sobre a checagem/reversão', null=True, verbose_name='Observação do Coordenador')),
                ('status_checagem', models.CharField(choices=[('EM_ESPERA', 'Em Espera'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ESPERA', max_length=15, verbose_name='Status da Checagem')),
                ('status', models.BooleanField(default=True, help_text='Define se o horário de checagem está ativo ou inativo', verbose_name='Ativo')),
                ('agendamento', models.ForeignKey(help_text='Agendamento relacionado à checagem/reversão', on_delete=django.db.models.deletion.PROTECT, related_name='horarios_checagem', to='siape.agendamentofichacliente', verbose_name='Agendamento')),
                ('consultor', models.ForeignKey(help_text='Usuário consultor que solicitou a checagem/reversão', on_delete=django.db.models.deletion.PROTECT, related_name='horarios_consultor', to=settings.AUTH_USER_MODEL, verbose_name='Consultor')),
                ('coordenador', models.ForeignKey(help_text='Usuário coordenador ou superior (hierarquia 3+) responsável pela checagem', on_delete=django.db.models.deletion.PROTECT, related_name='horarios_coordenador', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('tabulacao', models.ForeignKey(help_text='Tabulação relacionada à checagem/reversão', on_delete=django.db.models.deletion.PROTECT, related_name='horarios_checagem', to='siape.tabulacaoagendamento', verbose_name='Tabulação')),
            ],
            options={
                'verbose_name': 'Horário de Checagem',
                'verbose_name_plural': 'Horários de Checagem',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['coordenador', 'data'], name='siape_horar_coorden_23d26b_idx'),
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['consultor', 'data'], name='siape_horar_consult_e3739b_idx'),
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['data', 'hora'], name='siape_horar_data_7ede99_idx'),
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['status_checagem'], name='siape_horar_status__bfee81_idx'),
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['agendamento'], name='siape_horar_agendam_a7d3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='horariochecagem',
            index=models.Index(fields=['tabulacao'], name='siape_horar_tabulac_d33f8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horariochecagem',
            unique_together={('coordenador', 'agendamento', 'data', 'hora')},
        ),
    ]
