# Generated by Django 5.1 on 2025-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0014_remove_tabulacaocliente_cliente_and_more'),
    ]

    operations = [
        # As tabelas TabulacaoCliente e HistoricoTabulacao já foram removidas na migração 0010
        # Removendo operações desnecessárias que tentam remover novamente
        migrations.AlterField(
            model_name='dadosnegociacao',
            name='tc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor TC (quanto a empresa recebe na operação)', max_digits=5, null=True, verbose_name='TC'),
        ),
    ]
