# Generated by Django 5.1 on 2025-06-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siape', '0016_mark_tabulacaocliente_removed'),
    ]

    operations = [
        # Migração fake - os modelos já foram removidos manualmente
        # Não executa operações no banco, apenas marca como aplicada
    ]
